// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://douwddahfwzjdvycwcov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvdXdkZGFoZnd6amR2eWN3Y292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NTY5MzEsImV4cCI6MjA1NzQzMjkzMX0.Z4jtN1mwl2UxeFFxWU8EvseKqqZ07_ezj4L4jpfN_Yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);